'use strict';
// Source/DOM contract tests only; this does not claim rendered browser acceptance.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync('src/team_browser/static/tab_workspace.js','utf8');
const id='tab_'+'a'.repeat(32), profile={id:'local-one',revision:4,generation:3};
const snapshot=(over={})=>({profile_id:profile.id,generation:3,status:'ready',truncated:false,tabs:[{id,title:'<img src=x onerror=alert(1)>',origin:'https://example.test',active:true}],active_evidence:'dom_visibility_hint',focus:{status:'idle'},...over});
function setup() {
  const doc={activeElement:null};
  class El {constructor(tag){this.tagName=tag;this.children=[];this.dataset={};this.attrs={};this.listeners={};this.textContent='';} append(...a){this.children.push(...a);} replaceChildren(...a){this.children=a;} setAttribute(k,v){this.attrs[k]=v;} addEventListener(k,f){this.listeners[k]=f;} focus(){doc.activeElement=this;}}
  doc.createElement=t=>new El(t); const root=new El('section'), window={}; const scheduled=new Map();let n=0;
  const context={window,document:doc,URL,AbortController,setTimeout,clearTimeout};vm.runInNewContext(source,context);
  const calls=[],notices=[];let next=async()=>snapshot();
  const component=window.TeamNativeTabs.mount({document:doc,request:async(path,options)=>{calls.push({path,options});return next(path,options);},notify:x=>notices.push(x),schedule:(f,ms)=>{const id=++n;scheduled.set(id,{f,ms});return id;},cancel:id=>scheduled.delete(id)});
  const all=(el=root)=>[el,...el.children.flatMap(x=>all(x))];
  return {component,root,doc,calls,notices,scheduled,all,normalize:window.TeamNativeTabs.normalize,setNext:f=>next=f};
}
const settle=()=>new Promise(resolve=>setImmediate(resolve));
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return{promise,resolve};};
let count=0;async function test(name,fn){await fn();count++;console.log('ok '+count+' '+name);}
(async()=>{
 await test('Titles are text nodes; no arbitrary navigation or HTML is used',async()=>{const t=setup();t.component.activate(t.root,profile);await settle();assert(t.all().some(e=>e.textContent===snapshot().tabs[0].title));assert(!source.includes('innerHTML'));assert(!source.includes('location.href'));assert.equal(t.calls[0].path,'/tabs');t.component.deactivate();});
 await test('Foreign profile and generation response clears all tab choices',async()=>{for(const over of [{profile_id:'other'},{generation:4}]){const t=setup();t.setNext(async()=>snapshot(over));t.component.activate(t.root,profile);await settle();assert.equal(t.component.state.snapshot,null);assert.equal(t.all().filter(e=>e.dataset.nativeTab).length,0);t.component.deactivate();}});
 await test('Incomplete snapshots never expose selectable tabs',async()=>{const t=setup();t.setNext(async()=>snapshot({status:'limited',active_tab_id:null,truncated:true}));t.component.activate(t.root,profile);await settle();assert.equal(t.component.state.snapshot.status,'limited');assert.equal(t.all().filter(e=>e.dataset.nativeTab).length,0);t.component.deactivate();});
 await test('Malformed IDs, origin paths, duplicates and excessive entries reject',async()=>{const t=setup();for(const tabs of [[{...snapshot().tabs[0],id:'javascript:x'}],[{...snapshot().tabs[0],origin:'https://example.test/private?token=x'}],[...snapshot().tabs,...snapshot().tabs],Array(129).fill(snapshot().tabs[0])])assert.throws(()=>t.normalize(snapshot({tabs}),profile));});
 await test('Old selection completion cannot repaint a new profile',async()=>{const t=setup(),held=deferred();t.setNext(()=>held.promise);t.component.activate(t.root,profile);t.setNext(async()=>snapshot({profile_id:'other'}));t.component.activate(t.root,{...profile,id:'other'});await settle();held.resolve(snapshot());await settle();assert.equal(t.component.state.profile.id,'other');assert.equal(t.component.state.snapshot.status,'ready');t.component.deactivate();});
 await test('Expired metadata clears while a later read is still in flight',async()=>{const t=setup();t.component.activate(t.root,profile);await settle();const expiry=[...t.scheduled.values()].find(x=>x.ms===5000);assert(expiry);const held=deferred();t.setNext(()=>held.promise);const pending=t.component.poll();expiry.f();assert.equal(t.component.state.snapshot,null);assert.equal(t.all().filter(e=>e.dataset.nativeTab).length,0);held.resolve(snapshot());await pending;t.component.deactivate();});
 await test('Focus sends exact opaque ID, profile generation and revision',async()=>{const t=setup();t.component.activate(t.root,profile,'side');await settle();assert(t.root.className.includes('native-tabs-side'));t.setNext(async(path)=>path==='/tabs'?snapshot({focus:{status:'queued'}}):{profile_id:profile.id,generation:3,tab_id:id,outcome:'queued'});await t.component.focus(id);const call=t.calls.find(x=>x.path.endsWith('/tab-focus'));assert.deepEqual(JSON.parse(JSON.stringify(call.options.body)),{tab_id:id,generation:3,expected_revision:4});assert.equal(call.options.method,'POST');assert(t.all().some(x=>x.textContent==='Focus requested; waiting for the browser.'));t.component.deactivate();});
 await test('Unknown tab ID and deactivated controls send no mutations',async()=>{const t=setup();t.component.activate(t.root,profile);await settle();await t.component.focus('tab_'+'b'.repeat(32));t.component.deactivate();await t.component.focus(id);assert(!t.calls.some(x=>x.options?.method==='POST'));assert.equal(t.root.children.length,0);assert.equal(t.scheduled.size,0);});
 await test('Late focus result cannot restore a retired view',async()=>{const t=setup();t.component.activate(t.root,profile);await settle();const held=deferred();t.setNext(()=>held.promise);const pending=t.component.focus(id);t.component.deactivate();held.resolve({profile_id:profile.id,generation:3,tab_id:id,outcome:'queued'});await pending;assert.equal(t.component.state.snapshot,null);assert.equal(t.root.children.length,0);assert.equal(t.scheduled.size,0);});
 await test('Failed read removes former private titles',async()=>{const t=setup();t.component.activate(t.root,profile);await settle();t.setNext(async()=>{throw new Error('private detail');});await t.component.poll();assert.equal(t.component.state.snapshot,null);assert(!t.all().some(x=>x.textContent.includes('<img')));assert(!t.all().some(x=>x.textContent.includes('private detail')));t.component.deactivate();});
 console.log(`PASS: ${count} synthetic native-tab UI scenarios; no rendered browser.`);
})().catch(e=>{console.error(e);process.exitCode=1;});
